// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";

// Load .env.local first (higher priority), then .env as fallback — mirrors Next.js behavior
config({ path: ".env.local", override: false });
config({ path: ".env", override: false });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // directUrl bypasses the connection pooler for migrations
    // @ts-expect-error Prisma 7 supports directUrl but types may lag
    directUrl: process.env["DIRECT_URL"],
  },
});
